/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.mylyn.reviews.r4e.core.model.validation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

import org.eclipse.mylyn.reviews.r4e.core.model.R4EFileContext;

/**
 * A sample validator interface for {@link org.eclipse.mylyn.reviews.r4e.core.model.R4EItem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface R4EItemValidator {
	boolean validate();

	boolean validateXmlVersion(String value);
	boolean validateDescription(String value);
	boolean validateAddedById(String value);
	boolean validateFileContextList(EList<R4EFileContext> value);
	boolean validateRepositoryRef(String value);
	boolean validateProjectURIs(EList<String> value);
	boolean validateAuthorRep(String value);
	boolean validateSubmitted(Date value);
	boolean validateInfoAtt(EMap<String, String> value);
}
