/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.mylyn.reviews.r4e.core.model.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;

import org.eclipse.mylyn.reviews.r4e.core.model.R4EAnomalyType;
import org.eclipse.mylyn.reviews.r4e.core.model.R4EReview;
import org.eclipse.mylyn.reviews.r4e.core.model.R4EUserReviews;

/**
 * A sample validator interface for {@link org.eclipse.mylyn.reviews.r4e.core.model.R4EReviewGroup}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface R4EReviewGroupValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateFolder(String value);
	boolean validateDefaultEntryCriteria(String value);
	boolean validateAvailableProjects(EList<String> value);
	boolean validateAvailableComponents(EList<String> value);
	boolean validateDesignRuleLocations(EList<String> value);
	boolean validateXmlVersion(String value);
	boolean validateAvailableAnomalyTypes(EList<R4EAnomalyType> value);
	boolean validateAnomalyTypeKeyToReference(EMap<String, R4EAnomalyType> value);
	boolean validateReviewsMap(EMap<String, R4EReview> value);
	boolean validateUserReviews(EMap<String, R4EUserReviews> value);
}
