/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.mylyn.reviews.r4e.core.model.validation;

import java.util.Date;

import org.eclipse.mylyn.reviews.r4e.core.model.R4EReviewPhase;

/**
 * A sample validator interface for {@link org.eclipse.mylyn.reviews.r4e.core.model.R4EReviewPhaseInfo}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface R4EReviewPhaseInfoValidator {
	boolean validate();

	boolean validateEndDate(Date value);
	boolean validateType(R4EReviewPhase value);
	boolean validatePhaseOwnerID(String value);
	boolean validateStartDate(Date value);
}
