/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.eclipse.mylyn.reviews.r4e.core.model.validation;

import org.eclipse.emf.common.util.EList;

import org.eclipse.mylyn.reviews.r4e.core.model.R4EComment;
import org.eclipse.mylyn.reviews.r4e.core.model.R4EItem;
import org.eclipse.mylyn.reviews.r4e.core.model.R4EReview;

/**
 * A sample validator interface for {@link org.eclipse.mylyn.reviews.r4e.core.model.R4EUser}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface R4EUserValidator {
	boolean validate();

	boolean validateGroupPaths(EList<String> value);
	boolean validateSequenceIDCounter(int value);
	boolean validateAddedComments(EList<R4EComment> value);
	boolean validateAddedItems(EList<R4EItem> value);
	boolean validateReviewCreatedByMe(boolean value);
	boolean validateReviewInstance(R4EReview value);
	boolean validateXmlVersion(String value);
	boolean validateReviewCompleted(boolean value);
	boolean validateReviewCompletedCode(int value);
}
